on:
  push:
    branches: ["main"]

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build Zola site
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          BUILD_ONLY: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public